catastrophic error:  HTTPConnectionPool(host='10.44.0.52', port=8000): Max retries exceeded with url: /sites/api/v1/get_sites (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9793b7e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
catastrophic error:  HTTPConnectionPool(host='10.44.0.52', port=8000): Max retries exceeded with url: /sites/api/v1/get_single_cluster/46 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9780f55a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
